### ISSUE TITLE
Add an exclude windows list

### ISSUE THREAD

**Issue by Haozun** [joelpurra/xmouse-controls#14]
I met the same problem as #8 
I suggest you can add an exclude windows list, the specific windows in the exclude windows list will not autoraise(autofocus).
Then #8 can also be solved.

**Comment by binki** [comment]
XMouse-Controls merely sets registry keys which enable Windows's built-in focus follows mouse and autoraise behavior. I do not think Windows has a way to set an inclusion/exclusion list, but I don't know this for sure. However, since XMouse-Controls merely sets Windows settings and does not actively implement the feature, this can not be added to XMouse-Controls as it is unless if Windows provided a way to configure this.

I think implementing the feature you want would require an “active” approach which runs in the background all of the time and tries to focus and raise windows depending various conditions. It wouldn't simply be a new feature to this program, I think it'd make sense to be done as a different program/project.

**Comment by binki** [comment]
To avoid the issue you hit with this app's approach, I think your only option is to make sure your mouse is not on your text input area. Also, please consider using Windows's Feedback tool to let them know of the issue and give them enough information to know that you're using this program and the steps to recreate the issue.

**Comment by joelpurra** [comment]
@Haozun: as mentioned by @binki and in #8, this is an issue that the Windows team at Microsoft needs to address. Closing this issue as a duplicate.

Perhaps consider a custom script in AutoHotKey? I have no experience with that type of scripting though, and can't say if it it's possible -- but I do know AHK offers window selection/filtering.

- https://en.wikipedia.org/wiki/AutoHotkey
