### ISSUE TITLE
Is is possible to pause the app if a file is getting deleted for example

### ISSUE THREAD

**Issue by stephen147** [joelpurra/xmouse-controls#17]
When deleting a file for example and you hover past another window the delete box confirm window gets sent to the back if that option is enabled.

Is it possible to auto-pause the app when something like this happens? Maybe there are too many situations where a similar situation occurs like the properties window.

**Comment by joelpurra** [comment]
@stephen147: unfortunately such special handling is out of scope for X-Mouse Controls. Each program decides for themselves if each windows is standalone, or a modal window. This choice is usually made already when designing a program.

https://en.wikipedia.org/wiki/Modal_window

Some workarounds:

1. Disable active window raising -- just untick the checkbox. Some programs override this though, so not 100% effective.
1. Increase the delay to something that you are comfortable with. I usually recommend a few hundred milliseconds, say 100-300, but it could be higher depending on how often you encounter this issue.
1. Find a "dead" spot (where nothing happens if you click) somewhere on the screen, hold down the mouse button there, drag to the window you actually want focused, and let go. This way focus does not change until you have moved the mouse, but it's inconvenient to use often.

Does that help?

I'll close this issue, as it's out of scope. Do continue the discussion if you need clarification. Thanks for using X-Mouse Controls =)

**Comment by stephen147** [comment]
No, that's understandable and would most likely cause more issues than it's worth. After some usage of this you have to be smarter where you're mouse goes. And it's not so much of an issue now. 300ms is my setting and I'm good with that. Thanks for the reply.
