### ISSUE TITLE
Add Command-Line Options

### ISSUE THREAD

**Issue by pleappleappleap** [joelpurra/xmouse-controls#22]
This program works great.  The only thing I would want is the ability to specify the parameters on the command-line.  The program should just execute the requested action and then terminate.  The GUI should only come up if no parameters are specified on the command-line.

**Comment by joelpurra** [comment]
@pleappleappleap: sorry, no plans to add CLI arguments at this time. Mixing CLI and GUI functionality in a single .exe is not good practice; should be two different programs, if you ask me.

There's an answer on SuperUser which shows how to enable `SPI_SETACTIVEWINDOWTRACKING` using a powershell script though. Perhaps that will suffice as a base for scripting "all" parameters available in X-Mouse Controls?

- https://superuser.com/a/1209478
- https://github.com/joelpurra/xmouse-controls/search?q=SPI_SETACTIVEWINDOWTRACKING

Closing this issue, since the request is considered out of scope for X-Mouse Controls. Feel free to post follow-up questions anyways, or perhaps a nice powershell script for others to use =)
