### ISSUE TITLE
Feature request: Exclude windows elements and pop up windows?

### ISSUE THREAD

**Issue by rp1231** [joelpurra/xmouse-controls#27]
Hi, would it be possible to exclude windows elements and pop up windows from the xmouse behavior?
 Thanks

**Comment by binki** [comment]
X-Mouse Controls is not an active program. It simply alters certain registry keys that configure this feature in Windows. For Windows 9x and XP, Microsoft’s PowerToys program provided a UI to control these settings. For newer versions of Windows, there is no official UI, but the feature still exists and is configurable. X-Mouse Controls simply provides that UI to update the settings of a built-in Windows feature—it does not implement the feature itself.

The Windows settings which are tweaked are general and cover everything. There is no way to restrict it to specific windows that I know of. I suspect that Windows does not support this. But if it does, please provide details on how to edit the registry to achieve this.

If you really need this feature, you might look into an “active” window focus/raising manager program instead of a passive program like X-Mouse Controls.

If you are encountering a particular issue with how some program or Windows is behaving, please describe that in some detail. Someone might be able to suggest a workaround. See [usage](https://joelpurra.com/projects/X-Mouse_Controls/#usage) which mentions the left-click-and-drag workaround (though right-click-and-drag works in more scenarios).

**Comment by rp1231** [comment]
Oh I see,
I haven't really found any other programs that provide active window focus.

I was having some annoyances with the behavior change of pop up ui elements such as the start menu and the system tray menu. Also some other pop up elements that I can't recollect at the moment.

**Comment by joelpurra** [comment]
@rp1231: what @binki (thank you!) said is correct: if you want exceptions to the X-Mouse behavior provided by Windows (and enabled by X-Mouse Controls) you'd need a different program to manage those. I'll close this issue as this feature request is out of scope for X-Mouse Controls.

For workarounds for specific programs/ui elements, such as the start menu, you can find suggestions in other (closed) issues. Feel free to post a new issue if you've encountered something new or different =)
