### ISSUE TITLE
Breaks context menu in Windows 10

### ISSUE THREAD

**Issue by mw999** [joelpurra/xmouse-controls#9]
When window tracking is enabled and an icon is right clicked in the task bar, the context menu immediately disappears.

A temporary fix is adding a delay onto the window switch.

**Comment by binki** [comment]
It seems like there's a pixel or so of space between the icon in the task bar and the context menu. If you move your mouse up to the context menu while it's still animating, it will remain open. Another workaround, from the README, is to wait for the menu to open and then press and hold the right mouse button while moving the mouse up to the menu. That will prevent the menu from closing while your mouse passes over the pixel between the task bar and menu.

**Comment by binki** [comment]
Please also report this to Microsoft via the feedback app since they're the only people who can actually fix the root issue.

**Comment by mw999** [comment]
Have reported to Microsoft: https://aka.ms/K3w2ww

I doubt this will be seen however.

**Comment by joelpurra** [comment]
@mw999: setting a delay of 100-200 ms in X-Mouse Controls is my primary recommendation. This will also help with other cases where there are pixel-distances between two windows/parts/menus of a program.

The secondary workaround is click-drag as @binki mentions (thanks!), which would also help when the window-to-window distance is greater than the distance you move the mouse pointer in 100-200 ms.

As the issue also exists with other (usually third-party) programs, especially those with custom/styled systray menus, you'd probably have to use one of the workaround either way.

> https://insider.windows.com/en-us/fb/?contextid=215&feedbackid=bda85c83-5f8d-48e5-9681-322e720a5152&form=1
> This content is available only in the FeedbackHub app through the Windows 10 Anniversary Update

I can't see the contents on the website (see quote), but thank you for reporting the issue to Microsoft! I'm sure your feedback will be *read*, but also doubt that they will change anything, as this has been an issue with Windows for years -- since the Windows Vista Aero Glass UI, I believe.

Closing this issue, as it's outside of the control of X-Mouse Controls.

Thanks for using X-Mouse Controls, and do tell your friends about it =)

**Comment by binki** [comment]
@mw999 When I try to see the feedback, it says my account may not see it. Did you mark it private or something? If you are able/willing to make it public, we can upvote it.
